server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/admin/**, /events/**, /categories/**, /compilations/**
        - id: stat-server
          uri: lb://stat-server
          predicates:
            - Path=/hit, /stats
