server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_main_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
